### ISSUE TITLE
Fill in GPA Calculator section in Grades tab

### ISSUE THREAD

**Issue by AveryVine** [K-shamG/SSSC-Android-app#15]
**Is your feature request related to a problem? Please describe.**
We need a view where students can see all of their courses together, along with their general overall CGPA and their major CGPA.

**Describe the solution you'd like**
You’ll need to reference the following database operation:
- getting all courses

Run the calculations on the the courses you get, and list them somewhere on the screen (probably along the bottom?). There should also be a toggle in the Settings tab to show/hide in-progress courses from the GPA calculator tab.

**Additional context**
![IMG_4766](https://user-images.githubusercontent.com/17837126/64990146-33152680-d89d-11e9-8b1e-566f049ce494.png)

**Comment by liaocanada** [comment]
@AveryVine 
Are the colours on the left randomized or is it based on something?

**Comment by AveryVine** [comment]
Ooh, good question. It should be based off the colour the user selects for each course - except I forgot to put that spec in #21, the one that Derek worked on to add the Course objects to the database! So yeah, just skip it entirely for now, and do it without colours on the left side. We can make another small pass at the app later in the term when things cool down.
